"""Intelligence Persistence Connector — Phase HERALD-INTELLIGENCE-013.

Bridges the existing Decision Performance Intelligence into the new
IntelligenceStore, and summarizes persisted intelligence into the Agent
Memory Layer (ExecutionMemory) without mutating existing records.

Data flow:
    DecisionPerformanceEngine
        |  (existing store + feedback loop)
        v
    IntelligenceStore                 <- append-only persistence
        |
        v
    Agent Memory Layer (ExecutionMemory)  <- summaries via metadata (additive)

Additive only. Never blocks execution. Every public method is fail-safe:
returns False / None / {} instead of raising, and logs a warning.

Phase HERALD-INTELLIGENCE-013
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from governance.intelligence_store import IntelligenceStore

logger = logging.getLogger(__name__)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


class IntelligencePersistenceConnector:
    """Copies intelligence out of the live decision pipeline into durable storage.

    Design notes:
    - Never writes into the decision engine's own store; it only reads from it.
    - Persists five classes of records:
        * decisions       (recorded strategy / confidence / outcome)
        * evaluations     (post-execution evaluation results)
        * feedback        (feedback signals generated by the feedback loop)
        * strategy_metrics (periodic metric snapshots)
        * confidence       (confidence history entries)
    - Optionally attaches a summary to the Agent Memory Layer record for an
      execution (additive metadata only; existing fields are untouched).
    """

    def __init__(
        self,
        store: Optional[IntelligenceStore] = None,
        enabled: bool = True,
    ) -> None:
        self.enabled = enabled
        self.store = store if store is not None else IntelligenceStore()
        self._synced: Dict[str, int] = {
            "decisions": 0,
            "evaluations": 0,
            "feedback": 0,
            "strategy_metrics": 0,
            "confidence_history": 0,
        }

    # ------------------------------------------------------------------ #
    # Decision capture (engine -> store).

    def persist_decision_record(self, record: Any) -> bool:
        """Persist one DecisionRecord-like object into the store."""
        if not self.enabled:
            return False
        try:
            if hasattr(record, "to_dict"):
                payload = record.to_dict()
            elif isinstance(record, dict):
                payload = dict(record)
            else:
                return False
            ok = self.store.append_decision(payload)
            if ok:
                self._synced["decisions"] += 1
            return ok
        except Exception as exc:  # noqa: BLE001 - fail-safe
            logger.warning("persist_decision_record failed: %s", exc)
            return False

    def persist_evaluation(self, evaluation: Any) -> bool:
        """Persist one evaluation result (dict or object with to_dict)."""
        if not self.enabled:
            return False
        try:
            if hasattr(evaluation, "to_dict"):
                payload = evaluation.to_dict()
            elif isinstance(evaluation, dict):
                payload = dict(evaluation)
            else:
                return False
            ok = self.store.append_evaluation(payload)
            if ok:
                self._synced["evaluations"] += 1
            return ok
        except Exception as exc:  # noqa: BLE001
            logger.warning("persist_evaluation failed: %s", exc)
            return False

    def persist_feedback(self, feedback: Any) -> bool:
        """Persist one DecisionFeedback-like object into the store."""
        if not self.enabled:
            return False
        try:
            if hasattr(feedback, "to_dict"):
                payload = feedback.to_dict()
            elif isinstance(feedback, dict):
                payload = dict(feedback)
            else:
                return False
            ok = self.store.append_feedback(payload)
            if ok:
                self._synced["feedback"] += 1
            return ok
        except Exception as exc:  # noqa: BLE001
            logger.warning("persist_feedback failed: %s", exc)
            return False

    def persist_strategy_metrics(self, metrics: Any) -> bool:
        """Persist a strategy-metrics snapshot (DecisionMetrics-like object)."""
        if not self.enabled:
            return False
        try:
            if hasattr(metrics, "to_dict"):
                payload = metrics.to_dict()
            elif isinstance(metrics, dict):
                payload = dict(metrics)
            else:
                return False
            payload["recorded_at"] = _utc_now()
            ok = self.store.append_strategy_metrics(payload)
            if ok:
                self._synced["strategy_metrics"] += 1
            return ok
        except Exception as exc:  # noqa: BLE001
            logger.warning("persist_strategy_metrics failed: %s", exc)
            return False

    def persist_confidence(
        self,
        decision_id: str,
        confidence: float,
        strategy: Optional[str] = None,
        task_id: Optional[str] = None,
    ) -> bool:
        """Append a confidence-history entry."""
        if not self.enabled:
            return False
        try:
            ok = self.store.append_confidence({
                "decision_id": decision_id,
                "confidence": float(confidence),
                "strategy": strategy,
                "task_id": task_id,
            })
            if ok:
                self._synced["confidence_history"] += 1
            return ok
        except Exception as exc:  # noqa: BLE001
            logger.warning("persist_confidence failed: %s", exc)
            return False

    # ------------------------------------------------------------------ #
    # Bulk sync from the live pipeline (read-only on the pipeline side).

    def sync_from_engine(self, engine: Any, limit: int = 200) -> Dict[str, int]:
        """Pull persisted decisions + evaluations + metrics from an engine.

        Reads only: uses the engine's public read API and its store's read
        methods. Returns a dict of {section: count_persisted}.

        engine is expected to expose:
            - get_recent_decisions(limit=...) -> [DecisionRecord]
            - get_metrics() -> DecisionMetrics
        """
        if not self.enabled:
            return {}
        synced: Dict[str, int] = {}
        try:
            decisions = engine.get_recent_decisions(limit=limit)
            for decision in decisions:
                if self.persist_decision_record(decision):
                    synced["decisions"] = synced.get("decisions", 0) + 1
        except Exception as exc:  # noqa: BLE001
            logger.warning("sync decisions failed: %s", exc)

        try:
            metrics = engine.get_metrics()
            if metrics is not None and self.persist_strategy_metrics(metrics):
                synced["strategy_metrics"] = synced.get("strategy_metrics", 0) + 1
        except Exception as exc:  # noqa: BLE001
            logger.warning("sync strategy metrics failed: %s", exc)
        return synced

    def sync_feedback_from_loop(self, feedback_loop: Any, limit: int = 200) -> int:
        """Persist feedback history entries from a DecisionFeedbackLoop.

        Uses the loop's public get_recent_feedback() — read-only on the loop.
        """
        if not self.enabled:
            return 0
        count = 0
        try:
            entries = feedback_loop.get_recent_feedback(limit=limit)
            for entry in entries:
                if self.persist_feedback(entry):
                    count += 1
        except Exception as exc:  # noqa: BLE001
            logger.warning("sync feedback failed: %s", exc)
        return count

    # ------------------------------------------------------------------ #
    # Agent Memory Layer bridge (additive metadata only).

    def attach_to_execution_memory(
        self,
        memory: Any,
        execution_id: str,
        summary: Optional[Dict[str, Any]] = None,
    ) -> bool:
        """Attach an intelligence summary to an execution memory record.

        Read-modify-write preserving all existing fields: the summary is
        merged into record.metadata["intelligence"] only. The memory object
        must expose get_execution(id) -> record with .metadata and
        save_execution(record) -> id (ExecutionMemory contract).

        Returns True if a record existed and was updated; False otherwise.
        """
        if not self.enabled:
            return False
        try:
            record = memory.get_execution(execution_id)
            if record is None:
                return False
            intelligence = dict(summary or {})
            intelligence.setdefault("attached_at", _utc_now())
            merged = dict(record.metadata)
            merged["intelligence"] = intelligence
            record.metadata = merged
            memory.save_execution(record)
            return True
        except Exception as exc:  # noqa: BLE001
            logger.warning("attach_to_execution_memory failed: %s", exc)
            return False

    # ------------------------------------------------------------------ #
    # Reporting.

    def synced_counts(self) -> Dict[str, int]:
        """Counters of how many records this connector persisted."""
        return dict(self._synced)

    def storage_summary(self) -> Dict[str, Any]:
        """Human-friendly summary of persisted data."""
        try:
            counts = self.store.counts()
            return {
                "storage_path": str(self.store.storage_path),
                "format_version": self.store.format_version,
                "counts": counts,
                "total_records": sum(counts.values()),
                "enabled": self.enabled,
            }
        except Exception as exc:  # noqa: BLE001
            logger.warning("storage_summary failed: %s", exc)
            return {}